### ISSUE TITLE
Релиз аутха (финишная прямая)

### ISSUE THREAD

**Issue by physphile** [profcomff/webapp-ui#94]
## Дизайн
- [x] https://github.com/profcomff/design/issues/7

## ПМ
- [x] https://github.com/profcomff/.github/issues/64

## Бэкенд
- [x] https://github.com/profcomff/services-api/issues/48
- [x] https://github.com/profcomff/auth-api/issues/131
- [x] https://github.com/profcomff/auth-api/issues/132
- [x] https://github.com/profcomff/auth-api/issues/143
    - [x] https://github.com/profcomff/auth-api/issues/149
    - [x] https://github.com/profcomff/auth-api/issues/148
    - [x] https://github.com/profcomff/userdata-api/issues/12

## Фронтенд
- [ ]  [feature] [Страница редактирования пользователя](https://github.com/profcomff/webapp-ui/issues/212) 
- [ ] [feature] [Добавить email в "добавить метод входа](https://github.com/profcomff/webapp-ui/issues/194)~
- [ ] [feature] [Изменение "неизменяемых" полей](https://github.com/profcomff/webapp-ui/issues/192)
- [x] [bug] [Не работает привязка доп Oauth методов](https://github.com/profcomff/webapp-ui/issues/211)
- [x] [enhancement] [Поменять текст тост уведомлений](https://github.com/profcomff/webapp-ui/issues/196)
- [x] [bug] [Пустой тост на завершение сессии](https://github.com/profcomff/webapp-ui/issues/191)~
- [x] [bug] [Починить Toast уведомления](https://github.com/profcomff/webapp-ui/issues/156)
- [x]  [bug] [Убрать тост об изменении пароля при входе](https://github.com/profcomff/webapp-ui/issues/189)
- [x] [feature] https://github.com/profcomff/webapp-ui/issues/71
- [x] https://github.com/profcomff/design/issues/12
- [x] https://github.com/profcomff/webapp-ui/issues/164
- [x] https://github.com/profcomff/webapp-ui/issues/123
- [x] https://github.com/profcomff/webapp-ui/issues/130

**Comment by grigoriev-semyon** [comment]
а вы в курсе что прямые бесконечны

**Comment by dyakovri** [comment]
- [bug] [Не работает привязка доп Oauth методов](https://github.com/profcomff/webapp-ui/issues/211)
- [bug] [Починить Toast уведомления](https://github.com/profcomff/webapp-ui/issues/156)
- [enhancement] [Поменять текст тост уведомлений](https://github.com/profcomff/webapp-ui/issues/196)
- [bug] [Пустой тост на завершение сессии](https://github.com/profcomff/webapp-ui/issues/191)~
- [bug] [Убрать тост об изменении пароля при входе](https://github.com/profcomff/webapp-ui/issues/189)
- [feature] [Страница редактирования пользователя](https://github.com/profcomff/webapp-ui/issues/212) 
- [feature] [Добавить email в "добавить метод входа](https://github.com/profcomff/webapp-ui/issues/194)~
- [feature] [Изменение "неизменяемых" полей](https://github.com/profcomff/webapp-ui/issues/192)
