### ISSUE TITLE
Дизайн админки пользователей

### ISSUE THREAD

**Issue by dyakovri** [profcomff/webapp-ui#99]
### Подзадачи

- [x] #147
- [x] #144
- [x] #145
- [x] #146

**Comment by Arzangulyan** [comment]
Админка пользователей
- [ ] Экран с редактируемыми полями
- личные данные пользователя
- группы (админ, член профсоюза, студент)
- фотка
- [ ] Причесать экран со списком пользователей
- [ ] Выпадающее меню для фильтров в поиске пользователей

Админка юзердаты
*экран редактирования полей в юзердате — уточнить*

**Comment by Arzangulyan** [comment]
**Дерево с группами пользователей**
Функционал:
- создание групп и подгрупп
- перенос групп в другие группы
- настройка скоупов (прав доступа) группы
-

**Comment by Arzangulyan** [comment]
Первычный комментарий Ромы по тикету:

> Страница управление сервисами аутентификации и авторизации
> 
> Возможности:
> - Управление деревьями групп доступа
> - Управление списком доступов у конкретной группы (помнить, что внутренняя группа наследует список доступов группы-родителя)
> - Управление списком участников группы
> - Создание групп в дереве, перенос группы в дереве, удаление группы 
> 
> - Управление данными пользователей
> - Настройка групп полей полей пользователей (название группы, названия прав для доступа на чтение и управление этой группой)
> - Добавление/удаление полей у всех пользователей (список обязательных и необязательных данных о пользователе, настройка выбора поля: последнее значение/наиболее достоверное значение/все значения, тип данных значения)
> 
> - Список пользователей, с фильтрами по различным полям
> - Страница редактирования конкретного пользователя: просмотр всех данных пользователя из всех источников, ручная замена параметров, выдача группы 
>
